# Generated by Django 3.1.4 on 2021-01-18 20:51

from django.db import migrations, models
import generic.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='International format is preffered', max_length=27, validators=[generic.validators.phone_validator])),
                ('creator_link', models.URLField(max_length=127)),
                ('company_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Footer Data',
                'verbose_name_plural': 'Footer Data',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, default='static/images/default.png', help_text='1:1 aspect ratio required.', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, default='static/images/default.png', help_text='1:1 aspect ratio required.', null=True, upload_to='')),
                ('phone', models.CharField(help_text='International format is preffered', max_length=27, validators=[generic.validators.phone_validator])),
                ('start_time', models.CharField(max_length=31)),
                ('end_time', models.CharField(max_length=31)),
                ('extra_details', models.CharField(help_text="Relevant information abouct clinic's schedule", max_length=255)),
                ('specializations', models.ManyToManyField(to='generic.Specialization')),
            ],
        ),
    ]
