# Generated by Django 3.1.4 on 2020-12-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=2000)),
                ('creator_link', models.URLField(max_length=127)),
                ('company_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Footer Data',
                'verbose_name_plural': 'Footer Data',
            },
        ),
    ]
