# Generated by Django 3.1.4 on 2020-12-22 16:39

from django.db import migrations, models
import generic.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='International format is preffered', max_length=27, validators=[generic.validators.phone_validator])),
                ('creator_link', models.URLField(max_length=127)),
                ('company_email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Footer Data',
                'verbose_name_plural': 'Footer Data',
            },
        ),
    ]
