# Generated by Django 3.1.3 on 2020-12-02 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerdata',
            options={'verbose_name': 'Footer Data', 'verbose_name_plural': 'Footer Data'},
        ),
    ]
