# Generated by Django 3.1.3 on 2020-12-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_auto_20201202_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(max_length=200)),
                ('email_port', models.CharField(max_length=200)),
                ('email_host_user', models.CharField(max_length=200)),
                ('email_host_password', models.CharField(max_length=200)),
            ],
        ),
    ]
