# Generated by Django 3.1.4 on 2021-01-18 20:51

import accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generic', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(help_text='International format is preffered', max_length=27, validators=[accounts.validators.phone_validator])),
                ('personal_id', models.CharField(error_messages={'unique': 'A user with that personal ID already exists.'}, help_text='Do not include spaces', max_length=128, unique=True, validators=[accounts.validators.personal_id_validator], verbose_name='Personal ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active status')),
                ('is_connected', models.BooleanField(default=False, help_text='Describes the connection status of an user.', verbose_name='connection status')),
                ('is_client', models.BooleanField(default=False, help_text='A non-staff user with the client status.', verbose_name='client status')),
                ('is_operator', models.BooleanField(default=False, help_text='A non-staff user with the operator status.', verbose_name='operator status')),
                ('is_doctor', models.BooleanField(default=False, help_text='A non-staff user with the doctor status.', verbose_name='doctor status')),
                ('is_staff', models.BooleanField(default=False, help_text='An user without permissions, but can log into the admin site.', verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, help_text='An user with all permissions.', verbose_name='superuser status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('picture', models.ImageField(blank=True, help_text='1:1 aspect ratio required.', null=True, upload_to='')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generic.clinic')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generic.specialization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
