# Generated by Django 3.1.4 on 2020-12-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Unselect this if you are creating an operator user', verbose_name='active status'),
        ),
    ]
