# Generated by Django 3.1.4 on 2021-01-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210105_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='picture',
            field=models.ImageField(blank=True, help_text='1:1 aspect ratio required.', null=True, upload_to=''),
        ),
    ]
