# Generated by Django 3.1.4 on 2021-01-18 20:51

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorWorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_interval', models.SmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(55)])),
                ('monday_start', models.TimeField(blank=True, default=datetime.time(9, 0), null=True)),
                ('monday_end', models.TimeField(blank=True, default=datetime.time(17, 0), null=True)),
                ('tuesday_start', models.TimeField(blank=True, default=datetime.time(9, 0), null=True)),
                ('tuesday_end', models.TimeField(blank=True, default=datetime.time(17, 0), null=True)),
                ('wednesday_start', models.TimeField(blank=True, default=datetime.time(9, 0), null=True)),
                ('wednesday_end', models.TimeField(blank=True, default=datetime.time(17, 0), null=True)),
                ('thursday_start', models.TimeField(blank=True, default=datetime.time(9, 0), null=True)),
                ('thursday_end', models.TimeField(blank=True, default=datetime.time(17, 0), null=True)),
                ('friday_start', models.TimeField(blank=True, default=datetime.time(9, 0), null=True)),
                ('friday_end', models.TimeField(blank=True, default=datetime.time(17, 0), null=True)),
                ('saturday_start', models.TimeField(blank=True, default=datetime.time(9, 0), null=True)),
                ('saturday_end', models.TimeField(blank=True, default=datetime.time(17, 0), null=True)),
                ('sunday_start', models.TimeField(blank=True, default=datetime.time(9, 0), null=True)),
                ('sunday_end', models.TimeField(blank=True, default=datetime.time(17, 0), null=True)),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctorprofile')),
            ],
            options={
                'verbose_name': 'Doctor Working Hours',
                'verbose_name_plural': 'Doctor Working Hours',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
                ('doctor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='accounts.doctorprofile')),
            ],
        ),
    ]
