# Generated by Django 3.1.4 on 2021-01-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='end',
            field=models.TimeField(blank=True, null=True, verbose_name='Date Time'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='start',
            field=models.TimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
    ]
