# Generated by Django 3.1.4 on 2021-01-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20210111_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorworkinghours',
            options={'verbose_name': 'Doctor Working Hours', 'verbose_name_plural': 'Doctor Working Hours'},
        ),
    ]
