# Generated by Django 3.1.4 on 2021-01-11 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20210111_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='friday_end',
            field=models.TimeField(blank=True, default=datetime.time(17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='friday_start',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='monday_end',
            field=models.TimeField(blank=True, default=datetime.time(17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='monday_start',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='saturday_end',
            field=models.TimeField(blank=True, default=datetime.time(17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='saturday_start',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='sunday_end',
            field=models.TimeField(blank=True, default=datetime.time(17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='sunday_start',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='thursday_end',
            field=models.TimeField(blank=True, default=datetime.time(17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='thursday_start',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='tuesday_end',
            field=models.TimeField(blank=True, default=datetime.time(17, 0), null=True),
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='tuesday_start',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='wednesday_start',
            field=models.TimeField(blank=True, default=datetime.time(9, 0), null=True),
        ),
    ]
