# Generated by Django 3.1.4 on 2021-01-11 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_auto_20210111_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorworkinghours',
            name='wednesday_end',
            field=models.TimeField(blank=True, default=datetime.time(17, 0), null=True),
        ),
    ]
